### ISSUE TITLE
Vagrant Repo/Directory Name

### ISSUE THREAD

**Issue by chacken** [sous-chefs/golang#36]
There's not much you can do about this besides changing the meta name to chef-golang... but.. If the meta name does not match the directory name while using Vagrant, Chef complains that the template file does not exist in template/default/golang.sh.erb  (it looks in /golang/templates/default/ for some reason)

This can be easily fixed by simply renaming the directory after cloning, but it's an annoying bug to have to troubleshoot and I bet I'm not the only one who's had to do so.  Perhaps adding a warning in the README would suffice.

**Comment by jeffbyrnes** [comment]
The repo name now matches the cookbook name, thanks to its change in ownership. Closing this out.
