### ISSUE TITLE
allow installing a package version from github

### ISSUE THREAD

**Issue by grosser** [sous-chefs/golang#64]
atm it always installs master and then never updates ... 
I need to set it to a certain tag or sha ... is that possible ?

@mburns

**Comment by scalp42** [comment]
@grosser I don't think it's possible as it's doing a `go get`.

There are workarounds (I might tackle it down soon enough): https://stackoverflow.com/questions/30188499/how-to-do-go-get-on-a-specific-tag-of-a-github-repository

**Comment by grosser** [comment]
we no longer have that usecase atm since we got rid of that package, but might still be nice to add :)

**Comment by mburns** [comment]
hey @grosser and @scalp42 I've mostly just done housekeeping tasks, but I've got some free time to update that actual cookbook logic. If you have use cases or version requirements this cookbook could be better at, feel free mention them and I'll triage/solve what I can.

**Comment by jeffbyrnes** [comment]
Per @scalp42, this is not possible with `go get`, which the `go_package` resource wraps.

The modules functionality introduced in v1.11 & declared stable in v1.12 appear to be an answer of sorts, but aren‘t directly accessible via `go get`. As such, I’m going to close this out as something we cannot address with this cookbook.
