### ISSUE TITLE
Supermarket versions

### ISSUE THREAD

**Issue by HP41** [sous-chefs/golang#68]
`golang` on Supermarket has only versions upto `1.7.0`.
`chef-golang` on Supermarket is even older at `1.0.1 (2013)`

I was wondering if it's possible to push v3 that's currently the latest on this repo to Supermarket and if it already is, where is it?

Thanks!!!

**Comment by jeffbyrnes** [comment]
@HP41 we’ve moved this cookbook over to sous-chefs, and I’m working on setting up access to Supermarket for us to publish a new version.

**Comment by jeffbyrnes** [comment]
I’ve gone ahead & published all the outstanding versions to Supermarket. Working on a new one that improves things, too!
