### ISSUE TITLE
Setup for Sous-Chefs

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/golang#70]
Cookbook needs setting up for sous

- [x] metadata
- [x] terraform (admin)
- [x] standard files (bot)
- [x] cookstyle (bot)
- [x] labels standardise (bot)
- [x] github actions
- [x] circleci (admin)
- [x] rebase the files used

**Comment by jeffbyrnes** [comment]
I’ll work on setting all this up over the weekend, since I’m the one who brought it into the fold 🙂

**Comment by Xorima** [comment]
So the cookbook is now in terraform, all the things labelled (bot) will happen automatically over the next 24 hours

**Comment by jeffbyrnes** [comment]
What does “rebase the files used” mean in this context?

**Comment by Xorima** [comment]
Its something I did, it's basically a make sure there are no non-standard files left behind, eg. make/rake files, travis ci etc

**Comment by jeffbyrnes** [comment]
Looks like we’re all set then!
