### ISSUE TITLE
Deprecate Recipes

### ISSUE THREAD

**Issue by damacus** [sous-chefs/golang#74]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## 🙍 Problem Statement

Application & system cookbooks, should follow the Sous-Chefs standards and use custom resources, and library helpers to install and configure software. This cookbook still uses attributes and recipes. 

## :grey_question: Possible Solution

1) Introduce custom resources that are wrapped by the current recipes.
2) Add a warning to the recipes to use the custom resources directly
3) Deprecate/remove the current recipes

## :arrow_heading_up: Describe alternatives you've considered

Leave it as it is.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by MarkGibbons** [comment]
I've got a version that is in the final stages of testing.

**Comment by MarkGibbons** [comment]
I think we've reduced the recipe to a nice stub that calls resources with reasonable defaults.  I don't think we need to do anymore.  To me this issue looks resolved.  it's not perfectly clean but it's close enough.

**Comment by jeffbyrnes** [comment]
Yeah, we’ve satisfied the spirit of this issue.

If I get ambitious, I might cut one more, breaking version that dumps the attributes entirely, like how the `nginx` cookbook changed in v10.0.0.

**Comment by MarkGibbons** [comment]
Closing for now.
