### ISSUE TITLE
Update supermarket source url

### ISSUE THREAD

**Issue by jeremy-clerc** [sous-chefs/golang#77]
### :speaking_head: Foreword

https://supermarket.chef.io/cookbooks/golang -> `View Source` goes to https://github.com/NOX73/golang

## :ghost: Brief Description

https://github.com/NOX73/golang is gone

## :pancakes: Cookbook version

3.0.0

## Steps To Reproduce

1. Go to https://supermarket.chef.io/cookbooks/golang
2. Click on View Source
3. 404 not found

## :police_car: Expected behavior

Going to https://github.com/sous-chefs/golang

## :heavy_plus_sign: Additional context

Looking at the changelog, it seems the repo from NOX73 was first renamed to chef-golang

Now that the metadata is up to date in v3.0.0, could you reset / update the `source_url` used by https://supermarket.chef.io/cookbooks/golang ?

Thanks

**Comment by jeffbyrnes** [comment]
Thanks @jeremy-clerc! I’ll get this fixed up.

**Comment by jeffbyrnes** [comment]
All set with v3.0.1
