### ISSUE TITLE
node['golang']['scm'] not passed to golang resource

### ISSUE THREAD

**Issue by evandam** [sous-chefs/golang#88]
## :ghost: Brief Description

There's an attribute for `node['golang']['scm']` but setting it to `false` does not result in `git` and `mercurial` being installed.

## :pancakes: Cookbook version

`4.1.0`

## :woman_cook:  Chef-Infra Version

`15.15.0`

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

## Steps To Reproduce

```ruby
node.default['golang']['scm'] = false
include_recipe 'golang'
```

## :police_car: Expected behavior

Git and Mercurial are not installed.

Thanks folks!

**Comment by ramereth** [comment]
Looks like a pretty easy fix in the default recipe. Feel free to make a PR which addresses this!
