### ISSUE TITLE
Chef 17 support

### ISSUE THREAD

**Issue by askmike1** [sous-chefs/golang#96]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

Currently has `depends 'ark', '~> 5.0'`
Ark has updates in 6.0 to support Chef 17
Request is to support Chef 17

## :grey_question: Possible Solution

Allow ark 6.x

## :arrow_heading_up: Describe alternatives you've considered

n/a

## :heavy_plus_sign: Additional context

n/a

**Comment by detjensrobert** [comment]
This was fixed in #99
